# Note that single quote ' should be escaped by another single quote '
# Example(see: Can''t):     '.* ERR kernel: \[\s+\d+\.\d+\] /dev/sda3: Can''t open blockdev'
# Example: in code below - errors will be ignored:
# IF: test case name: tests/test_dbg.py::test_a
# OR
# IF: Redmine issue active AND branch is 202106 AND sn2 in platform
# OR
# IF: GitHub issue is active
#- Errors_list:
#    - '.* ERR \d+'
#    - 'ERR can''t do \d+'
#  Conditions:
#    - Affected_test_cases:
#      - tests/test_dbg.py::test_a
#    - Redmine:
#      - 2829157
#      Branch:
#      - 202106
#      Platform:
#      - sn2
#    - GitHub:
#      - https://github.com/Azure/sonic-buildimage/issues/9811

# Errors which should be ignored in tests which doing reboot/reload
- Errors_list:
    - '.* ERR mlxfwmanager: LIBMVPD: MVPD_READ4 failed on offset:.*'
    - '.* ERR \/container: docker cmd: kill for .* failed .*'
    - '.* ERR pmon#thermalctld: Caught exception while running thermal policy .*'
    - '.* ERR (caclmgrd|\/hostcfgd).*: :- poll_descriptors: readData error: Unable to read redis reply.*'
    - '.* INFO hostcfgd.*:     raise ConnectionError.*'
    - '.* ERR systemd.*: kdump-tools.service: Ignoring invalid environment assignment .* /etc/default/kdump-tools.*'
    - '.* ERR hw-management: Path /var/run/hw-management/events/.* doesn''t exist'
    - '.* ERR dhclient.*send_packet: Network is unreachable.*'
    - '.* ERR dhclient.*send_packet: please consult README file regarding broadcast address.*'
    - '.* ERR dhclient.*Failed to send 300 byte long packet over .*'
    - '.* ERR dhclient.*No buffer space available.*'
    - '.* ERR syncd#SDK:.*Invalid port type.*'
    - '.* ERR syncd#SDK:.*mlnx_sai_utils.c.*Failed attribs dispatch.*'
    - '.* ERR syncd#SDK:.*mlnx_sai_bridge.c.*Unexpected bridge type.*'
    - '.* ERR syncd#SDK:.*mlnx_sai_utils.c.*Failed getting attrib.*'
    - '.* WARNING syncd#SDK:.*skipping since it causes crash:.*'
    - '.* ERR swss#orchagent:.*ASIC sensors : failed to get .*'
    - '.* ERR syncd#SDK:.*Unsupported debug counter type.*'
    - '.* ERR syncd#SDK:.*Invalid port counter.*'
    - '.* INFO systemd.*Start.*Kernel crash dump capture service.*'
    - '.* ERR syncd#SDK:.*mlnx_initialize_switch: Transaction mode should be enabled, enabling now.*'
    - '.* NOTICE syncd#SDK:.*Create trap.*'
    - '.* ERR neighbor_advertiser: EVERFLOW.* table does not exist.*'
    - '.* INFO systemd.*: Finished Kernel crash dump capture service.*'
    - '.* ERR syncd#SDK:.*\[SAI_BRIDGE.ERR\].*Isolation group is only supported for bridge port type port.*'
    - '.* ERR syncd#SDK:.*\[SAI_PORT.ERR\].*Port index not found in DB by log id.*'
    - '.* ERR teamd#teammgrd:.*/usr/bin/teamd -k -t.*'
    - '.* ERR caclmgrd.*: message repeated \d+ times: .*poll_descriptors: readData error: Unable to read redis reply.*'
    - '.* ERR syncd#SDK:.*\[SAI_PORT.ERR\].*mlnx_sai_port.c.*Not supported stats ID.*'
    - '.* ERR syncd#SDK:.*\[SX_API_BULK_COUNTER.ERR\].*Invalid value of port counter-groups bitmap.*'
    - '.* ERR syncd#SDK:.*\[SAI_PORT.ERR\].*mlnx_sai_port.c.* Failed to convert counter IDs to counter types bitmap.*'
    - '.* ERR syncd#SDK:.*\[SAI_PORT.ERR\].*mlnx_sai_port.c.* Failed to create buffer: Parameter Error.*'
    - '.* ERR syncd#SDK:.*\[SAI_PORT.ERR\].*mlnx_sai_port.c.* Failed to allocate SDK buffer.*'
    - '.* ERR swss#\w+syncd: :- readData: netlink reports .* on reading a netlink socket.*'
    - '.* ERR syncd#SDK:.*\[SX_API_INTERNAL.ERR\].*Failed command read at communication channel: Connection reset by peer.*'
    - '.* ERR \/hostcfgd:.*sudo systemctl (enable|disable).*failed. RC: 1.*'
    - '.* ERR \/hostcfgd:.*Feature.*failed to be\s+(enabled and started|stopped and disabled).*'
    - '.* ERR (swss#portsyncd|teamd#teamsyncd):.*netlink reports an error=-33 on reading a netlink socket.*'
    - '.* ERR systemd-udevd.*: could not read from ''\/sys\/module\/acpi_cpufreq\/initstate'': No such device.*'
    - '.* (ERR|WARNING) syncd#(SAI|SDK):.*Shared memory of the.*already exists,\s*destroying it and re-creating.*'
    - '.* ERR swss#orchagent:.*removeLag: Failed to remove (ref count 1|non-empty) LAG PortChannel.*'
    - '.* ERR \/hostcfgd:.*error returned by select.*'
  Conditions:
    - Affected_test_cases:
      # Canonical
      - tests/nightly/app_extension/test_app_extension_reboot.py::test_app_start_delay_after_reboot
      - tests/nightly/auto_negotition/test_auto_neg.py::TestAutoNeg::test_auto_neg_conf
      - tests/nightly/copp/test_copp.py::test_copp_policer
      - tests/nightly/fdb/test_fdb_basic.py::TestFdbBasic::test_fdb_aging_time_expire
      - tests/nightly/fec/test_fec.py::TestFec::test_fec_capabilities_loopback_ports
      - tests/nightly/fec/test_fec.py::TestFec::test_fec_capabilities_hosts_ports
      - tests/nightly/fec/test_fec.py::TestFec::test_negative_fec
      - tests/nightly/fec/test_fec.py::TestFec::test_fec_bug_2705016
      - tests/nightly/p4/sampling_example/test_entry_scaling.py::TestEntryScaling::test_scaling_entries
      - tests/nightly/p4/sampling_example/test_entry_priority.py::test_entries_with_different_priority
      - tests/nightly/p4/sampling_example/test_entry_priority.py::test_entries_with_same_priority
      - tests/nightly/p4/sampling_example/test_entry_advance.py::TestEntryTraffic::test_enable_disable_p4_sampling
      - tests/nightly/p4/sampling_example/test_entry_advance.py::TestEntryTraffic::test_p4_sampling_traffic_concussive
      - tests/nightly/p4/examples_application/test_reboot/test_reboot.py::test_p4_examples_reboot
      - tests/nightly/lag/test_lag.py::test_core_functionality_with_reboot
      - tests/nightly/lag/test_lag.py::test_lag_min_links
      - tests/nightly/lag/test_lag.py::test_lag_members_scale
      - tests/nightly/lag/test_lag.py::test_lags_scale
      - tests/nightly/lag/test_lag.py::test_port_cannot_be_added_to_lag
      # Community
      - pc/test_po_update.py::test_po_update_io_no_loss
      - vxlan/test_vnet_route_leak.py::test_vnet_route_leak

- Errors_list:
    - '.* ERR pmon#chassis_db_init: Fail to decode DMI /sys/firmware/dmi/entries/2-0/raw due to FileNotFoundError\(2, ''No such file or directory''\)'
    - '.* ERR watchdogutil: Failed to get watchdog module'
    - '.* ERR kernel: \[\s+\d+\.\d+\] /dev/sda3: Can''t open blockdev'
    - '.* ERR healthd: Failed to read from file \/var\/run\/hw-management\/led\/led_status_capability - FileNotFoundError.*No such file or directory.*'
    - '.* ERR healthd: Failed to write.*file \/var\/run\/hw-management\/led\/led_status_green - FileNotFoundError.*No such file or directory.*'
  Conditions:
    - Platform:
      - simx

- Errors_list:
    - '.* ERR hostcfgd: sonic-kdump-config --disable - failed: return code - 1, output:#012None'
    - '.* ERR hostcfgd: sonic-kdump-config --memory 0M-2G:256M,2G-4G:320M,4G-8G:384M,8G-:448M - failed: return code - 1, output:#012None'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/fec/test_fec.py
      Platform:
      - sn5600_simx
      Redmine:
      - 2951102

# Ignores for LAG/LACP tests
- Errors_list:
    - '.* ERR.*hostcfgd: ''sudo systemctl stop macsec.service'' failed. RC: 5, output: None.*'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/lag/test_lag.py

# Below ignores from temp_log_analyzer_ignores.txt in LAG folder
- Errors_list:
    - '.* ERR \/hostcfgd: Unexpected state value ''always_enabled'' for feature .*'
    - '.* ERR caclmgrd\[.*\]: :- initializeGlobalConfig: Sonic database config global file doesn''t exist at .*'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/lag/test_lag.py::test_core_functionality_with_reboot
      - tests/nightly/lag/test_lag.py::test_port_cannot_be_added_to_lag
      - tests/nightly/lag/test_lag.py::test_lag_members_scale
      - tests/nightly/lag/test_lag.py::test_lags_scale
      # From ngts/tests/nightly/app_extension/temp_log_analyzer_ignores.txt
      - tests/nightly/app_extension/test_app_extension_reboot.py
      - tests/nightly/app_extension/test_app_extension_basic.py::test_repo_management

- Errors_list:
    - '.* WARNING syncd#SDK: \[LAG\.WARNING\] \[sx_lag_port_group_get\] incomplete logport list retrieving.*'
    - '.* WARNING syncd#SDK:.* \[.*] mlnx_sai_switch.c\[.*\]- event_thread_func: sx_api_host_ifc_recv on callback fd returned unknown port, waiting for next packet.*'
    - '.* ERR teamd#tlm_teamd: :- get_dump: Can''t get dump for LAG ''PortChannel\d+''.*'
    - '.* ERR kernel: \[.*\] mlxsw_minimal 2-0048: Reg cmd access failed \(.*\)'
    - '.* ERR kernel: \[.*\] mlxsw_minimal 2-0048: Could not acquire lock'
    - '.* ERR kernel: \[.*\] mlxsw_minimal 2-0048: Failed to query PWM'
    - '.* ERR kernel: \[.*\] mlxsw_minimal 2-0048: Failed to write PWM'
    - '.* ERR pmon#syseepromd: Failed to load platform-specific eeprom from deprecated plugin.*'
    - '.* WARNING pmon#syseepromd: Failed to load platform-specific eeprom from sonic_platform package due to KeyError.*'
    - '.* ERR \/hostcfgd: :- poll_descriptors: readData error: Unable to read redis reply.*'
    - '.* ERR \/hostcfgd: error returned by select.*'
    - '.* ERR syncd#SDK: :- translateVidToRid: unable to get RID for VID oid:0x.*'
    - '.* ERR kernel.*mlxsw_minimal.*HW semaphore is not released.*'
    - '.* ERR kernel.*mlxsw_minimal.*Cmd exec failed.*opcode.*opcode_mod.*'
    - '.* ERR kernel.*mlxsw_minimal.*Cmd exec failed.*'
    - '.* ERR teamd#tlm_teamd: :- process_add_queue: Can''t connect to teamd after .* attempts.*'
    - '.* ERR syncd#SDK: :- updateSupportedBufferPoolCounters: BUFFER_POOL_WATERMARK_STAT_COUNTER: counter SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES is not supported on buffer pool .*, rv: SAI_STATUS_NOT_IMPLEMENTED'
    - '.* INFO kernel: .* teamd.*: segfault at b0 ip .* sp .* error 4 in libteam.*'
    - '.* ERR snmp#snmpd.*: ioctl \d+ returned -1.*'
    - '.* ERR pmon#sensord: Error getting sensor data: mlxsw.*: Kernel interface error.*'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/lag/test_lag.py::test_core_functionality_with_reboot
      - tests/nightly/lag/test_lag.py::test_port_cannot_be_added_to_lag
      - tests/nightly/lag/test_lag.py::test_lag_members_scale
      - tests/nightly/lag/test_lag.py::test_lags_scale
# Finished ignores from temp_log_analyzer_ignores.txt in LAG folder

- Errors_list:
    - '.* WARNING syncd#SDK: \[HOST_INTERFACE\.WARNING\] Receive event of FW SOS.*'
    - '.* ERR kernel: \[.*\] mlxsw_minimal 2-0048: Could not acquire lock.*'
    - '.* ERR kernel: \[.*\] mlxsw_minimal 2-0048: Reg cmd access failed \(.*\).*'
    - '.* ERR kernel: \[.*\] mlxsw_minimal 2-0048: Reg cmd access status failed \(.*\).*'
    - '.* ERR kernel: \[.*\] mlxsw_minimal 2-0048: HW semaphore is not released.*'
    - '.* ERR kernel: \[.*\] mlxsw_minimal 2-0048: Cmd exec failed \(.*\).*'
    - '.* ERR kernel: \[.*\] mlxsw_minimal 2-0048 sfp\d+: Eeprom query failed.*'
    - '.* ERR kernel: \[.*\] mlxsw_minimal 2-0048: Failed to query PWM.*'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/show_techsupport
      - show_techsupport/test_techsupport.py::test_techsupport
      Redmine:
      - 2723566

# From ngts/tests/nightly/arp/log_analyzer_ignores.txt
- Errors_list:
    - '.* ERR swss#orchagent.*Failed to remove ref count.*\d+.*LAG.*PortChannel.*'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/arp/test_arp.py

# From ngts/tests/nightly/auto_negotition/negative_auto_neg_log_analyzer_ignores
- Errors_list:
    - '.* ERR syncd#SDK: \[SAI_PORT.ERR\] mlnx_sai_port.c\[.*\]- mlnx_port_speeds_merge: Port \[Speed\[.*\] configuration is invalid.*'
    - '.* ERR syncd#SDK: \[SAI_PORT.ERR\] mlnx_sai_port.c\[.*\]- mlnx_port_update_speed: Failed to merge speeds, interface types and auto_neg.*'
    - '.* ERR syncd#SDK: \[SAI_PORT.ERR\] mlnx_sai_port.c\[.*\]- mlnx_port_attr_set: Failed to update speed.*'
    - '.* ERR syncd#SDK: \[SAI_UTILS.ERR\] mlnx_sai_utils.c\[.*\]- sai_set_attribute: Failed set attrib dispatch.*'
    - '.* ERR syncd#SDK: :- sendApiResponse: api SAI_COMMON_API_SET failed in syncd mode: SAI_STATUS_INVALID_ATTR_VALUE_.*'
    - '.* ERR syncd#SDK: :- processQuadEvent: VID: oid:.* RID: oid:.*'
    - '.* ERR syncd#SDK: :- processQuadEvent: attr: SAI_PORT_ATTR_.*INTERFACE_TYPE:.*SAI_PORT_INTERFACE_TYPE_.*'
    - '.* ERR syncd#SDK: :- processQuadEvent: attr: SAI_PORT_ATTR_AUTO_NEG_MODE:.*'
    - '.* ERR swss#orchagent: :- set: set status: SAI_STATUS_INVALID_ATTR_VALUE_.*'
    - '.* ERR swss#orchagent: :- doPortTask: Failed to set port Ethernet\d+.*interface type to .*'
    - '.* ERR swss#orchagent: :- setPortAutoNeg: Failed to set AutoNeg \d+ to port pid:\d+.*'
    - '.* ERR swss#orchagent: :- handleSaiSetStatus: Encountered failure in set operation, exiting orchagent.*'
    - '.* ERR syncd#SDK: \[SAI_PORT.ERR\] mlnx_sai_port.c\[.*\]- mlnx_port_speeds_merge: Port \[.*\] configuration doesn''t match mask for \d+ lanes.*'
    - '.* ERR syncd#SDK: :- processQuadEvent: attr: SAI_PORT_ATTR_SPEED: \d+.*'
    - '.* ERR swss#orchagent: :- handleSaiSetStatus: Encountered SAI_STATUS_INVALID_ATTR_VALUE_0 in set operation.*'
    - '.* ERR swss#orchagent: :- doPortTask: Failed to set port Ethernet\d+ speed from \d+ to \d+.*'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/auto_negotition/test_auto_neg_negative.py::TestAutoNegNegative::test_negative_config_advertised_speeds
      - tests/nightly/auto_negotition/test_auto_neg_negative.py::TestAutoNegNegative::test_negative_config_advertised_types
      - tests/nightly/auto_negotition/test_auto_neg_negative.py::TestAutoNegNegative::test_negative_advertised_speed_type_mismatch
      - tests/nightly/auto_negotition/test_auto_neg.py::TestAutoNeg::test_auto_neg_toggle_peer_port

# From ngts/tests/nightly/fdb/log_analyzer_ignores.txt
- Errors_list:
    - '.* ERR swss#orchagent.*doAppSwitchTableTask.*Unsupported switch attribute ordered_ecmp.*'
    - '.* WARNING syncd#SDK:.*Not supported attribute SAI_TUNNEL_ATTR_DECAP_DSCP_MODE.*'
    - '.* WARNING syncd#SDK:.*sai_set_attribute: Failed attribs check, key:tunnel ID.*'
    - '.* ERR syncd#SDK.*sendApiResponse: api SAI_COMMON_API_SET failed in syncd mode: SAI_STATUS_ATTR_NOT_SUPPORTED.*'
    - '.* ERR syncd#SDK.*processQuadEvent.*VID.*oid.*RID.*oid.*'
    - '.* ERR syncd#SDK.*processQuadEvent.*attr.*SAI_TUNNEL_ATTR_DECAP_DSCP_MODE.*SAI_TUNNEL_DSCP_MODE_PIPE_MODEL.*'
    - '.* ERR swss#orchagent.*SAI_STATUS_ATTR_NOT_SUPPORTED.*'
    - '.* ERR swss#orchagent.*setTunnelAttribute.*Failed to set attribute dscp_mode with value pipe.*'
    - '.* ERR syncd#SDK.*updateSupportedBufferPoolCounters: BUFFER_POOL_WATERMARK_STAT_COUNTER: counter SAI_BUFFER_POOL_STAT_XOFF_ROOM_WATERMARK_BYTES is not supported on buffer pool oid:.*, rv: SAI_STATUS_NOT_IMPLEMENTED.*'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/fdb/test_fdb_basic.py::TestFdbBasic::test_fdb_aging_time_expire

# Ignores from ngts/tests/nightly/p4/examples_application/conftest.py
- Errors_list:
    - '.* ERR syncd#SDK.*__sdk_bridge_db_get_bridge failed.*'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/p4/examples_application/test_reboot/test_reboot.py::test_p4_examples_reboot
      - tests/nightly/p4/examples_application/test_p4_examples_app.py::test_p4_examples_feature_state
      Redmine:
      - 2890809

- Errors_list:
    - '.* ERR swss#orchagent.*addOperation.*Vxlan tunnel .* is already exists'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/p4/examples_application/test_reboot/test_reboot.py::test_p4_examples_reboot
      - tests/nightly/p4/examples_application/test_p4_examples_app.py::test_p4_examples_feature_state
      Redmine:
      - 2919698

- Errors_list:
    - '.* ERR swss#vxlanmgrd.*doVxlanCreateTask: Cannot create vxlan.*'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/p4/examples_application/test_reboot/test_reboot.py::test_p4_examples_reboot
      - tests/nightly/p4/examples_application/test_p4_examples_app.py::test_p4_examples_feature_state
      - vxlan/test_vnet_route_leak.py::test_vnet_route_leak
      Redmine:
      - 2920504

# From ngts/tests/nightly/p4/sampling_example/p4_sampling_loganalyzer_ignore.txt
- Errors_list:
    - '.* ERR syncd#SDK: \[SPAN.ERR\] SPAN module already initialized'
    - '.* ERR swss#orchagent: :- removeTunnelNextHop: Remove Tunnel next hop unable to find EVPN VTEP.*'
    - '.* ERR swss#orchagent: :- removeOverlayNextHops: Tunnel Nexthop .*delete failed.*'
    - '.* ERR syncd#SAI:.*\[SAI_SWITCH.ERR\].*mlnx_sai_switch.c.*Shared memory of the SAI already exists, destroying it and re-creating'
    - '.* WARNING syncd#SAI.*\[SAI_SWITCH.WARNING\].*mlnx_sai_switch.c.*sai_qos_db_create.*Shared memory of the SAI QOS already exists, destroying it and re-creating'
    - '.* WARNING syncd#SAI.*\[SAI_SWITCH.WARNING\].*mlnx_sai_switch.c.*sai_buffer_db_create.*Shared memory of the SAI buffer already exists, destroying it and re-creating'
    - '.* WARNING syncd#SAI.*\[SAI_SWITCH.WARNING\].*mlnx_sai_switch.c.*sai_acl_db_create.*Shared memory of the SAI ACL already exists, destroying it and re-creating'
    - '.* WARNING syncd#SAI.*\[SAI_SWITCH.WARNING\].*mlnx_sai_switch.c.*sai_tunnel_db_create.*Shared memory of the SAI TUNNEL already exists, destroying it and re-creating'
    - '.* WARNING syncd#SDK.*\[SXD_DPT.WARNING\].*sxd_dpt_init().*Shared memory of the DPT already exists,destroying it and re-creating'
    - '.* ERR /hostcfgd: Unexpected state value ''always_enabled'' for feature.*'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/p4/sampling_example/test_entry_advance.py::TestEntryTraffic::test_enable_disable_p4_sampling
      - tests/nightly/p4/sampling_example/test_entry_advance.py::TestEntryTraffic::test_p4_sampling_traffic_concussive
      - tests/nightly/p4/sampling_example/test_entry_priority.py::test_entries_with_different_priority
      - tests/nightly/p4/sampling_example/test_entry_priority.py::test_entries_with_same_priority
      - tests/nightly/p4/sampling_example/test_entry_scaling.py::TestEntryScaling::test_scaling_entries

- Errors_list:
    - '.* ERR swss#orchagent: :- removeLag: Failed to remove ref count.*\d+.*LAG PortChannel.*'
  Conditions:
    - Affected_test_cases:
      - tests/push_build_tests/L3/crm/test_crm.py::test_crm_route
      - tests/push_build_tests/L3/crm/test_crm.py::test_crm_neighbor_and_nexthop
      - tests/push_build_tests/L3/crm/test_crm.py::test_crm_nexthop_group_and_member
      - tests/push_build_tests/L3/crm/test_crm.py::test_crm_fdb_entry
      - tests/push_build_tests/L3/crm/test_crm.py::test_crm_acl
      - pc/test_po_update.py::test_po_update_io_no_los
      - vxlan/test_vnet_route_leak.py::test_vnet_route_leak
      Redmine:
      - 2615940

- Errors_list:
    - '.* ERR swss#orchagent: :- removeLag: Failed to remove non-empty LAG PortChannel.*'
  Conditions:
    - Affected_test_cases:
      - pc/test_po_update.py::test_po_update
      Redmine:
      - 2615940

- Errors_list:
    - '.*ERR kernel:.*mlxsw_minimal .* Eeprom query failed.*'
  Conditions:
    - Affected_test_cases:
      - tests/nightly/show_techsupport/test_techsupport.py::test_techsupport_mellanox_sdk_dump
      Redmine:
        - 2940773

- Errors_list:
    - '.*ERR pmon#thermalctld: Failed to run thermal policy all fan and psu presence.*'
  Conditions:
    - Affected_test_cases:
      - platform_tests/test_platform_info.py::test_show_platform_temperature_mocked
      Redmine:
        - 2943278

- Errors_list:
    - '.*ERR.*dhcp_relay#dhcrelay\[\d+\]:\sparse_option_buffer:\smalformed\soption\sdhcp6\.<unknown>\s\(code 29797\):\soption\slength\sexceeds\soption\sbuffer\slength\.'
    - '.*ERR.*dhcp_relay#dhcrelay\[\d+\]:\smessage\srepeated\s\d+\stimes:\s\[\sparse_option_buffer:\smalformed\soption\sdhcp6\.<unknown>\s\(code 29797\):\soption\slength\sexceeds\soption\sbuffer\slength\.'
  Conditions:
    - Affected_test_cases:
      - tests/push_build_tests/L3/dhcp_relay/test_dhcp6_relay.py::TestDHCP6Relay::test_dhcpv6_relay_client_request_with_malformed_payload

- Errors_list:
    - '.* ERR syncd#SDK: \[SAI_BUFFER.ERR\] mlnx_sai_buffer.c\[2199\]- mlnx_sai_buffer_create_pool_hw: Pool creation failed. sx_status:5, message No More Resources.'
    - '.* ERR syncd#SDK: :- sendApiResponse: api SAI_COMMON_API_CREATE failed in syncd mode: SAI_STATUS_INSUFFICIENT_RESOURCES'
    - '.* ERR syncd#SDK: :- processQuadEvent: attr: SAI_BUFFER_POOL_ATTR_SIZE: 0'
    - '.* ERR syncd#SDK: :- processQuadEvent: attr: SAI_BUFFER_POOL_ATTR_TYPE: SAI_BUFFER_POOL_TYPE_INGRESS'
    - '.* ERR syncd#SDK: :- processQuadEvent: attr: SAI_BUFFER_POOL_ATTR_THRESHOLD_MODE: SAI_BUFFER_POOL_THRESHOLD_MODE_DYNAMIC'
    - '.* ERR swss#orchagent: :- create: create status: SAI_STATUS_INSUFFICIENT_RESOURCES'
    - '.* ERR swss#orchagent: :- createZeroBufferProfile: Failed to create dynamic zero buffer pool for PFC WD: -4'
    - '.* ERR syncd#SDK: \[COS_DB_SB.ERR\] \[CREATE\]:No available Pool to use \(existed pools number=5, pool dir=0\)'
    - '.* ERR syncd#SDK: \[COS_SB.ERR\] sx_cos_db_pool_set\(SX_ACCESS_CMD_CREATE\): No More Resources'
    - '.* WARNING syncd#SDK: \[COS_SB.WARNING\] Failed in cos_sb_pool_param_set_cb\(\) , error: No More Resources'
    - '.* WARNING syncd#SDK: \[CORE_API.WARNING\] Failed in cos_pool_param_set_cb_wrapper\(\) , error: No More Resources'
    - '.* WARNING syncd#SDK: \[SX_API_COS.WARNING\] sx_api_cos_pool_set failed. err: 5'
  Conditions:
    - Affected_test_cases:
      - pfcwd/test_pfcwd_timer_accuracy.py::TestPfcwdAllTimer::test_pfcwd_timer_accuracy
      Redmine:
        - 2954026
